services:
  nginx:
    image: nginx:latest
    container_name: asterflow-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    container_name: asterflow-backend
    restart: always
    env_file: .env
    # Removed public ports exposure (access only via nginx)
    volumes:
      - /var/spool/asterisk/monitor:/var/spool/asterisk/monitor
      - /var/spool/asterisk/voicemail:/var/spool/asterisk/voicemail
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend_v3
      args:
        - VITE_ASTERISK_IP=${VITE_ASTERISK_IP} # For production builds
    container_name: asterflow-frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "80"
