from typing import Optional
from sqlmodel import Field, SQLModel
from datetime import datetime, date


class AlembicVersionConfig(SQLModel, table=True):
    __tablename__ = 'alembic_version_config'
    version_num: str = Field(primary_key=True)


class Extensions(SQLModel, table=True):
    __tablename__ = 'extensions'
    id: int = Field(primary_key=True)
    context: str = Field()
    exten: str = Field()
    priority: int = Field()
    app: str = Field()
    appdata: str = Field()


class Iaxfriends(SQLModel, table=True):
    __tablename__ = 'iaxfriends'
    id: int = Field(primary_key=True)
    name: str = Field()
    type: Optional[str] = Field(default=None, nullable=True)
    username: Optional[str] = Field(default=None, nullable=True)
    mailbox: Optional[str] = Field(default=None, nullable=True)
    secret: Optional[str] = Field(default=None, nullable=True)
    dbsecret: Optional[str] = Field(default=None, nullable=True)
    context: Optional[str] = Field(default=None, nullable=True)
    regcontext: Optional[str] = Field(default=None, nullable=True)
    host: Optional[str] = Field(default=None, nullable=True)
    ipaddr: Optional[str] = Field(default=None, nullable=True)
    port: Optional[int] = Field(default=None, nullable=True)
    defaultip: Optional[str] = Field(default=None, nullable=True)
    sourceaddress: Optional[str] = Field(default=None, nullable=True)
    mask: Optional[str] = Field(default=None, nullable=True)
    regexten: Optional[str] = Field(default=None, nullable=True)
    regseconds: Optional[int] = Field(default=None, nullable=True)
    accountcode: Optional[str] = Field(default=None, nullable=True)
    mohinterpret: Optional[str] = Field(default=None, nullable=True)
    mohsuggest: Optional[str] = Field(default=None, nullable=True)
    inkeys: Optional[str] = Field(default=None, nullable=True)
    outkeys: Optional[str] = Field(default=None, nullable=True)
    language: Optional[str] = Field(default=None, nullable=True)
    callerid: Optional[str] = Field(default=None, nullable=True)
    cid_number: Optional[str] = Field(default=None, nullable=True)
    sendani: Optional[str] = Field(default=None, nullable=True)
    fullname: Optional[str] = Field(default=None, nullable=True)
    trunk: Optional[str] = Field(default=None, nullable=True)
    auth: Optional[str] = Field(default=None, nullable=True)
    maxauthreq: Optional[int] = Field(default=None, nullable=True)
    requirecalltoken: Optional[str] = Field(default=None, nullable=True)
    encryption: Optional[str] = Field(default=None, nullable=True)
    transfer: Optional[str] = Field(default=None, nullable=True)
    jitterbuffer: Optional[str] = Field(default=None, nullable=True)
    forcejitterbuffer: Optional[str] = Field(default=None, nullable=True)
    disallow: Optional[str] = Field(default=None, nullable=True)
    allow: Optional[str] = Field(default=None, nullable=True)
    codecpriority: Optional[str] = Field(default=None, nullable=True)
    qualify: Optional[str] = Field(default=None, nullable=True)
    qualifysmoothing: Optional[str] = Field(default=None, nullable=True)
    qualifyfreqok: Optional[str] = Field(default=None, nullable=True)
    qualifyfreqnotok: Optional[str] = Field(default=None, nullable=True)
    timezone: Optional[str] = Field(default=None, nullable=True)
    adsi: Optional[str] = Field(default=None, nullable=True)
    amaflags: Optional[str] = Field(default=None, nullable=True)
    setvar: Optional[str] = Field(default=None, nullable=True)


class Meetme(SQLModel, table=True):
    __tablename__ = 'meetme'
    bookid: int = Field(primary_key=True)
    confno: str = Field()
    starttime: Optional[datetime] = Field(default=None, nullable=True)
    endtime: Optional[datetime] = Field(default=None, nullable=True)
    pin: Optional[str] = Field(default=None, nullable=True)
    adminpin: Optional[str] = Field(default=None, nullable=True)
    opts: Optional[str] = Field(default=None, nullable=True)
    adminopts: Optional[str] = Field(default=None, nullable=True)
    recordingfilename: Optional[str] = Field(default=None, nullable=True)
    recordingformat: Optional[str] = Field(default=None, nullable=True)
    maxusers: Optional[int] = Field(default=None, nullable=True)
    members: int = Field()


class Musiconhold(SQLModel, table=True):
    __tablename__ = 'musiconhold'
    name: str = Field(primary_key=True)
    mode: Optional[str] = Field(default=None, nullable=True)
    directory: Optional[str] = Field(default=None, nullable=True)
    application: Optional[str] = Field(default=None, nullable=True)
    digit: Optional[str] = Field(default=None, nullable=True)
    sort: Optional[str] = Field(default=None, nullable=True)
    format: Optional[str] = Field(default=None, nullable=True)
    stamp: Optional[datetime] = Field(default=None, nullable=True)
    loop_last: Optional[str] = Field(default=None, nullable=True)


class MusiconholdEntry(SQLModel, table=True):
    __tablename__ = 'musiconhold_entry'
    name: str = Field(primary_key=True)
    position: int = Field(primary_key=True)
    entry: str = Field()


class PsAors(SQLModel, table=True):
    __tablename__ = 'ps_aors'
    id: str = Field(primary_key=True)
    contact: Optional[str] = Field(default=None, nullable=True)
    default_expiration: Optional[int] = Field(default=None, nullable=True)
    mailboxes: Optional[str] = Field(default=None, nullable=True)
    max_contacts: Optional[int] = Field(default=None, nullable=True)
    minimum_expiration: Optional[int] = Field(default=None, nullable=True)
    remove_existing: Optional[str] = Field(default=None, nullable=True)
    qualify_frequency: Optional[int] = Field(default=None, nullable=True)
    authenticate_qualify: Optional[str] = Field(default=None, nullable=True)
    maximum_expiration: Optional[int] = Field(default=None, nullable=True)
    outbound_proxy: Optional[str] = Field(default=None, nullable=True)
    support_path: Optional[str] = Field(default=None, nullable=True)
    qualify_timeout: Optional[float] = Field(default=None, nullable=True)
    voicemail_extension: Optional[str] = Field(default=None, nullable=True)
    remove_unavailable: Optional[str] = Field(default=None, nullable=True)
    qualify_2xx_only: Optional[str] = Field(default=None, nullable=True)


class PsAsteriskPublications(SQLModel, table=True):
    __tablename__ = 'ps_asterisk_publications'
    id: str = Field(primary_key=True)
    devicestate_publish: Optional[str] = Field(default=None, nullable=True)
    mailboxstate_publish: Optional[str] = Field(default=None, nullable=True)
    device_state: Optional[str] = Field(default=None, nullable=True)
    device_state_filter: Optional[str] = Field(default=None, nullable=True)
    mailbox_state: Optional[str] = Field(default=None, nullable=True)
    mailbox_state_filter: Optional[str] = Field(default=None, nullable=True)


class PsAuths(SQLModel, table=True):
    __tablename__ = 'ps_auths'
    id: str = Field(primary_key=True)
    auth_type: Optional[str] = Field(default=None, nullable=True)
    nonce_lifetime: Optional[int] = Field(default=None, nullable=True)
    md5_cred: Optional[str] = Field(default=None, nullable=True)
    password: Optional[str] = Field(default=None, nullable=True)
    realm: Optional[str] = Field(default=None, nullable=True)
    username: Optional[str] = Field(default=None, nullable=True)
    refresh_token: Optional[str] = Field(default=None, nullable=True)
    oauth_clientid: Optional[str] = Field(default=None, nullable=True)
    oauth_secret: Optional[str] = Field(default=None, nullable=True)
    password_digest: Optional[str] = Field(default=None, nullable=True)
    supported_algorithms_uas: Optional[str] = Field(default=None, nullable=True)
    supported_algorithms_uac: Optional[str] = Field(default=None, nullable=True)


class PsContacts(SQLModel, table=True):
    __tablename__ = 'ps_contacts'
    # WARNING: No primary key found for ps_contacts - using auto-generated id
    id: Optional[int] = Field(default=None, primary_key=True)
    contact_id: Optional[str] = Field(default=None, nullable=True)
    uri: Optional[str] = Field(default=None, nullable=True)
    expiration_time: Optional[int] = Field(default=None, nullable=True)
    qualify_frequency: Optional[int] = Field(default=None, nullable=True)
    outbound_proxy: Optional[str] = Field(default=None, nullable=True)
    path: Optional[str] = Field(default=None, nullable=True)
    user_agent: Optional[str] = Field(default=None, nullable=True)
    qualify_timeout: Optional[float] = Field(default=None, nullable=True)
    reg_server: Optional[str] = Field(default=None, nullable=True)
    authenticate_qualify: Optional[str] = Field(default=None, nullable=True)
    via_addr: Optional[str] = Field(default=None, nullable=True)
    via_port: Optional[int] = Field(default=None, nullable=True)
    call_id: Optional[str] = Field(default=None, nullable=True)
    endpoint: Optional[str] = Field(default=None, nullable=True)
    prune_on_boot: Optional[str] = Field(default=None, nullable=True)
    qualify_2xx_only: Optional[str] = Field(default=None, nullable=True)


class PsDomainAliases(SQLModel, table=True):
    __tablename__ = 'ps_domain_aliases'
    id: str = Field(primary_key=True)
    domain: Optional[str] = Field(default=None, nullable=True)


class PsEndpointIdIps(SQLModel, table=True):
    __tablename__ = 'ps_endpoint_id_ips'
    id: str = Field(primary_key=True)
    endpoint: Optional[str] = Field(default=None, nullable=True)
    match: Optional[str] = Field(default=None, nullable=True)
    srv_lookups: Optional[str] = Field(default=None, nullable=True)
    match_header: Optional[str] = Field(default=None, nullable=True)
    match_request_uri: Optional[str] = Field(default=None, nullable=True)


class PsEndpoints(SQLModel, table=True):
    __tablename__ = 'ps_endpoints'
    id: str = Field(primary_key=True)
    transport: Optional[str] = Field(default=None, nullable=True)
    aors: Optional[str] = Field(default=None, nullable=True)
    auth: Optional[str] = Field(default=None, nullable=True)
    context: Optional[str] = Field(default=None, nullable=True)
    disallow: Optional[str] = Field(default=None, nullable=True)
    allow: Optional[str] = Field(default=None, nullable=True)
    direct_media: Optional[str] = Field(default=None, nullable=True)
    connected_line_method: Optional[str] = Field(default=None, nullable=True)
    direct_media_method: Optional[str] = Field(default=None, nullable=True)
    direct_media_glare_mitigation: Optional[str] = Field(default=None, nullable=True)
    disable_direct_media_on_nat: Optional[str] = Field(default=None, nullable=True)
    dtmf_mode: Optional[str] = Field(default=None, nullable=True)
    external_media_address: Optional[str] = Field(default=None, nullable=True)
    force_rport: Optional[str] = Field(default=None, nullable=True)
    ice_support: Optional[str] = Field(default=None, nullable=True)
    identify_by: Optional[str] = Field(default=None, nullable=True)
    mailboxes: Optional[str] = Field(default=None, nullable=True)
    moh_suggest: Optional[str] = Field(default=None, nullable=True)
    outbound_auth: Optional[str] = Field(default=None, nullable=True)
    outbound_proxy: Optional[str] = Field(default=None, nullable=True)
    rewrite_contact: Optional[str] = Field(default=None, nullable=True)
    rtp_ipv6: Optional[str] = Field(default=None, nullable=True)
    rtp_symmetric: Optional[str] = Field(default=None, nullable=True)
    send_diversion: Optional[str] = Field(default=None, nullable=True)
    send_pai: Optional[str] = Field(default=None, nullable=True)
    send_rpid: Optional[str] = Field(default=None, nullable=True)
    timers_min_se: Optional[int] = Field(default=None, nullable=True)
    timers: Optional[str] = Field(default=None, nullable=True)
    timers_sess_expires: Optional[int] = Field(default=None, nullable=True)
    callerid: Optional[str] = Field(default=None, nullable=True)
    callerid_privacy: Optional[str] = Field(default=None, nullable=True)
    callerid_tag: Optional[str] = Field(default=None, nullable=True)
    # TODO: Field '100rel' is not a valid Python identifier. Skipped for now.
    aggregate_mwi: Optional[str] = Field(default=None, nullable=True)
    trust_id_inbound: Optional[str] = Field(default=None, nullable=True)
    trust_id_outbound: Optional[str] = Field(default=None, nullable=True)
    use_ptime: Optional[str] = Field(default=None, nullable=True)
    use_avpf: Optional[str] = Field(default=None, nullable=True)
    media_encryption: Optional[str] = Field(default=None, nullable=True)
    inband_progress: Optional[str] = Field(default=None, nullable=True)
    call_group: Optional[str] = Field(default=None, nullable=True)
    pickup_group: Optional[str] = Field(default=None, nullable=True)
    named_call_group: Optional[str] = Field(default=None, nullable=True)
    named_pickup_group: Optional[str] = Field(default=None, nullable=True)
    device_state_busy_at: Optional[int] = Field(default=None, nullable=True)
    fax_detect: Optional[str] = Field(default=None, nullable=True)
    t38_udptl: Optional[str] = Field(default=None, nullable=True)
    t38_udptl_ec: Optional[str] = Field(default=None, nullable=True)
    t38_udptl_maxdatagram: Optional[int] = Field(default=None, nullable=True)
    t38_udptl_nat: Optional[str] = Field(default=None, nullable=True)
    t38_udptl_ipv6: Optional[str] = Field(default=None, nullable=True)
    tone_zone: Optional[str] = Field(default=None, nullable=True)
    language: Optional[str] = Field(default=None, nullable=True)
    one_touch_recording: Optional[str] = Field(default=None, nullable=True)
    record_on_feature: Optional[str] = Field(default=None, nullable=True)
    record_off_feature: Optional[str] = Field(default=None, nullable=True)
    rtp_engine: Optional[str] = Field(default=None, nullable=True)
    allow_transfer: Optional[str] = Field(default=None, nullable=True)
    allow_subscribe: Optional[str] = Field(default=None, nullable=True)
    sdp_owner: Optional[str] = Field(default=None, nullable=True)
    sdp_session: Optional[str] = Field(default=None, nullable=True)
    tos_audio: Optional[str] = Field(default=None, nullable=True)
    tos_video: Optional[str] = Field(default=None, nullable=True)
    sub_min_expiry: Optional[int] = Field(default=None, nullable=True)
    from_domain: Optional[str] = Field(default=None, nullable=True)
    from_user: Optional[str] = Field(default=None, nullable=True)
    mwi_from_user: Optional[str] = Field(default=None, nullable=True)
    dtls_verify: Optional[str] = Field(default=None, nullable=True)
    dtls_rekey: Optional[str] = Field(default=None, nullable=True)
    dtls_cert_file: Optional[str] = Field(default=None, nullable=True)
    dtls_private_key: Optional[str] = Field(default=None, nullable=True)
    dtls_cipher: Optional[str] = Field(default=None, nullable=True)
    dtls_ca_file: Optional[str] = Field(default=None, nullable=True)
    dtls_ca_path: Optional[str] = Field(default=None, nullable=True)
    dtls_setup: Optional[str] = Field(default=None, nullable=True)
    srtp_tag_32: Optional[str] = Field(default=None, nullable=True)
    media_address: Optional[str] = Field(default=None, nullable=True)
    redirect_method: Optional[str] = Field(default=None, nullable=True)
    set_var: Optional[str] = Field(default=None, nullable=True)
    cos_audio: Optional[int] = Field(default=None, nullable=True)
    cos_video: Optional[int] = Field(default=None, nullable=True)
    message_context: Optional[str] = Field(default=None, nullable=True)
    force_avp: Optional[str] = Field(default=None, nullable=True)
    media_use_received_transport: Optional[str] = Field(default=None, nullable=True)
    accountcode: Optional[str] = Field(default=None, nullable=True)
    user_eq_phone: Optional[str] = Field(default=None, nullable=True)
    moh_passthrough: Optional[str] = Field(default=None, nullable=True)
    media_encryption_optimistic: Optional[str] = Field(default=None, nullable=True)
    rpid_immediate: Optional[str] = Field(default=None, nullable=True)
    g726_non_standard: Optional[str] = Field(default=None, nullable=True)
    rtp_keepalive: Optional[int] = Field(default=None, nullable=True)
    rtp_timeout: Optional[int] = Field(default=None, nullable=True)
    rtp_timeout_hold: Optional[int] = Field(default=None, nullable=True)
    bind_rtp_to_media_address: Optional[str] = Field(default=None, nullable=True)
    voicemail_extension: Optional[str] = Field(default=None, nullable=True)
    mwi_subscribe_replaces_unsolicited: Optional[str] = Field(default=None, nullable=True)
    deny: Optional[str] = Field(default=None, nullable=True)
    permit: Optional[str] = Field(default=None, nullable=True)
    acl: Optional[str] = Field(default=None, nullable=True)
    contact_deny: Optional[str] = Field(default=None, nullable=True)
    contact_permit: Optional[str] = Field(default=None, nullable=True)
    contact_acl: Optional[str] = Field(default=None, nullable=True)
    subscribe_context: Optional[str] = Field(default=None, nullable=True)
    fax_detect_timeout: Optional[int] = Field(default=None, nullable=True)
    contact_user: Optional[str] = Field(default=None, nullable=True)
    preferred_codec_only: Optional[str] = Field(default=None, nullable=True)
    asymmetric_rtp_codec: Optional[str] = Field(default=None, nullable=True)
    rtcp_mux: Optional[str] = Field(default=None, nullable=True)
    allow_overlap: Optional[str] = Field(default=None, nullable=True)
    refer_blind_progress: Optional[str] = Field(default=None, nullable=True)
    notify_early_inuse_ringing: Optional[str] = Field(default=None, nullable=True)
    max_audio_streams: Optional[int] = Field(default=None, nullable=True)
    max_video_streams: Optional[int] = Field(default=None, nullable=True)
    webrtc: Optional[str] = Field(default=None, nullable=True)
    dtls_fingerprint: Optional[str] = Field(default=None, nullable=True)
    incoming_mwi_mailbox: Optional[str] = Field(default=None, nullable=True)
    bundle: Optional[str] = Field(default=None, nullable=True)
    dtls_auto_generate_cert: Optional[str] = Field(default=None, nullable=True)
    follow_early_media_fork: Optional[str] = Field(default=None, nullable=True)
    accept_multiple_sdp_answers: Optional[str] = Field(default=None, nullable=True)
    suppress_q850_reason_headers: Optional[str] = Field(default=None, nullable=True)
    trust_connected_line: Optional[str] = Field(default=None, nullable=True)
    send_connected_line: Optional[str] = Field(default=None, nullable=True)
    ignore_183_without_sdp: Optional[str] = Field(default=None, nullable=True)
    codec_prefs_incoming_offer: Optional[str] = Field(default=None, nullable=True)
    codec_prefs_outgoing_offer: Optional[str] = Field(default=None, nullable=True)
    codec_prefs_incoming_answer: Optional[str] = Field(default=None, nullable=True)
    codec_prefs_outgoing_answer: Optional[str] = Field(default=None, nullable=True)
    stir_shaken: Optional[str] = Field(default=None, nullable=True)
    send_history_info: Optional[str] = Field(default=None, nullable=True)
    allow_unauthenticated_options: Optional[str] = Field(default=None, nullable=True)
    t38_bind_udptl_to_media_address: Optional[str] = Field(default=None, nullable=True)
    geoloc_incoming_call_profile: Optional[str] = Field(default=None, nullable=True)
    geoloc_outgoing_call_profile: Optional[str] = Field(default=None, nullable=True)
    incoming_call_offer_pref: Optional[str] = Field(default=None, nullable=True)
    outgoing_call_offer_pref: Optional[str] = Field(default=None, nullable=True)
    stir_shaken_profile: Optional[str] = Field(default=None, nullable=True)
    security_negotiation: Optional[str] = Field(default=None, nullable=True)
    security_mechanisms: Optional[str] = Field(default=None, nullable=True)
    send_aoc: Optional[str] = Field(default=None, nullable=True)
    overlap_context: Optional[str] = Field(default=None, nullable=True)
    tenantid: Optional[str] = Field(default=None, nullable=True)
    suppress_moh_on_sendonly: Optional[str] = Field(default=None, nullable=True)


class PsGlobals(SQLModel, table=True):
    __tablename__ = 'ps_globals'
    id: str = Field(primary_key=True)
    max_forwards: Optional[int] = Field(default=None, nullable=True)
    user_agent: Optional[str] = Field(default=None, nullable=True)
    default_outbound_endpoint: Optional[str] = Field(default=None, nullable=True)
    debug: Optional[str] = Field(default=None, nullable=True)
    endpoint_identifier_order: Optional[str] = Field(default=None, nullable=True)
    max_initial_qualify_time: Optional[int] = Field(default=None, nullable=True)
    default_from_user: Optional[str] = Field(default=None, nullable=True)
    keep_alive_interval: Optional[int] = Field(default=None, nullable=True)
    regcontext: Optional[str] = Field(default=None, nullable=True)
    contact_expiration_check_interval: Optional[int] = Field(default=None, nullable=True)
    default_voicemail_extension: Optional[str] = Field(default=None, nullable=True)
    disable_multi_domain: Optional[str] = Field(default=None, nullable=True)
    unidentified_request_count: Optional[int] = Field(default=None, nullable=True)
    unidentified_request_period: Optional[int] = Field(default=None, nullable=True)
    unidentified_request_prune_interval: Optional[int] = Field(default=None, nullable=True)
    default_realm: Optional[str] = Field(default=None, nullable=True)
    mwi_tps_queue_high: Optional[int] = Field(default=None, nullable=True)
    mwi_tps_queue_low: Optional[int] = Field(default=None, nullable=True)
    mwi_disable_initial_unsolicited: Optional[str] = Field(default=None, nullable=True)
    ignore_uri_user_options: Optional[str] = Field(default=None, nullable=True)
    use_callerid_contact: Optional[str] = Field(default=None, nullable=True)
    send_contact_status_on_update_registration: Optional[str] = Field(default=None, nullable=True)
    taskprocessor_overload_trigger: Optional[str] = Field(default=None, nullable=True)
    norefersub: Optional[str] = Field(default=None, nullable=True)
    allow_sending_180_after_183: Optional[str] = Field(default=None, nullable=True)
    all_codecs_on_empty_reinvite: Optional[str] = Field(default=None, nullable=True)
    default_auth_algorithms_uas: Optional[str] = Field(default=None, nullable=True)
    default_auth_algorithms_uac: Optional[str] = Field(default=None, nullable=True)


class PsInboundPublications(SQLModel, table=True):
    __tablename__ = 'ps_inbound_publications'
    id: str = Field(primary_key=True)
    endpoint: Optional[str] = Field(default=None, nullable=True)
    # TODO: Field 'event_asterisk-devicestate' is not a valid Python identifier. Skipped for now.
    # TODO: Field 'event_asterisk-mwi' is not a valid Python identifier. Skipped for now.


class PsOutboundPublishes(SQLModel, table=True):
    __tablename__ = 'ps_outbound_publishes'
    id: str = Field(primary_key=True)
    expiration: Optional[int] = Field(default=None, nullable=True)
    outbound_auth: Optional[str] = Field(default=None, nullable=True)
    outbound_proxy: Optional[str] = Field(default=None, nullable=True)
    server_uri: Optional[str] = Field(default=None, nullable=True)
    from_uri: Optional[str] = Field(default=None, nullable=True)
    to_uri: Optional[str] = Field(default=None, nullable=True)
    event: Optional[str] = Field(default=None, nullable=True)
    max_auth_attempts: Optional[int] = Field(default=None, nullable=True)
    transport: Optional[str] = Field(default=None, nullable=True)
    multi_user: Optional[str] = Field(default=None, nullable=True)
    # TODO: Field '@body' is not a valid Python identifier. Skipped for now.
    # TODO: Field '@context' is not a valid Python identifier. Skipped for now.
    # TODO: Field '@exten' is not a valid Python identifier. Skipped for now.


class PsRegistrations(SQLModel, table=True):
    __tablename__ = 'ps_registrations'
    id: str = Field(primary_key=True)
    auth_rejection_permanent: Optional[str] = Field(default=None, nullable=True)
    client_uri: Optional[str] = Field(default=None, nullable=True)
    contact_user: Optional[str] = Field(default=None, nullable=True)
    expiration: Optional[int] = Field(default=None, nullable=True)
    max_retries: Optional[int] = Field(default=None, nullable=True)
    outbound_auth: Optional[str] = Field(default=None, nullable=True)
    outbound_proxy: Optional[str] = Field(default=None, nullable=True)
    retry_interval: Optional[int] = Field(default=None, nullable=True)
    forbidden_retry_interval: Optional[int] = Field(default=None, nullable=True)
    server_uri: Optional[str] = Field(default=None, nullable=True)
    transport: Optional[str] = Field(default=None, nullable=True)
    support_path: Optional[str] = Field(default=None, nullable=True)
    fatal_retry_interval: Optional[int] = Field(default=None, nullable=True)
    line: Optional[str] = Field(default=None, nullable=True)
    endpoint: Optional[str] = Field(default=None, nullable=True)
    support_outbound: Optional[str] = Field(default=None, nullable=True)
    contact_header_params: Optional[str] = Field(default=None, nullable=True)
    max_random_initial_delay: Optional[int] = Field(default=None, nullable=True)
    security_negotiation: Optional[str] = Field(default=None, nullable=True)
    security_mechanisms: Optional[str] = Field(default=None, nullable=True)


class PsResourceList(SQLModel, table=True):
    __tablename__ = 'ps_resource_list'
    id: str = Field(primary_key=True)
    list_item: Optional[str] = Field(default=None, nullable=True)
    event: Optional[str] = Field(default=None, nullable=True)
    full_state: Optional[str] = Field(default=None, nullable=True)
    notification_batch_interval: Optional[int] = Field(default=None, nullable=True)
    resource_display_name: Optional[str] = Field(default=None, nullable=True)


class PsSubscriptionPersistence(SQLModel, table=True):
    __tablename__ = 'ps_subscription_persistence'
    id: str = Field(primary_key=True)
    packet: Optional[str] = Field(default=None, nullable=True)
    src_name: Optional[str] = Field(default=None, nullable=True)
    src_port: Optional[int] = Field(default=None, nullable=True)
    transport_key: Optional[str] = Field(default=None, nullable=True)
    local_name: Optional[str] = Field(default=None, nullable=True)
    local_port: Optional[int] = Field(default=None, nullable=True)
    cseq: Optional[int] = Field(default=None, nullable=True)
    tag: Optional[str] = Field(default=None, nullable=True)
    endpoint: Optional[str] = Field(default=None, nullable=True)
    expires: Optional[int] = Field(default=None, nullable=True)
    contact_uri: Optional[str] = Field(default=None, nullable=True)
    prune_on_boot: Optional[str] = Field(default=None, nullable=True)
    generator_data: Optional[str] = Field(default=None, nullable=True)


class PsSystems(SQLModel, table=True):
    __tablename__ = 'ps_systems'
    id: str = Field(primary_key=True)
    timer_t1: Optional[int] = Field(default=None, nullable=True)
    timer_b: Optional[int] = Field(default=None, nullable=True)
    compact_headers: Optional[str] = Field(default=None, nullable=True)
    threadpool_initial_size: Optional[int] = Field(default=None, nullable=True)
    threadpool_auto_increment: Optional[int] = Field(default=None, nullable=True)
    threadpool_idle_timeout: Optional[int] = Field(default=None, nullable=True)
    threadpool_max_size: Optional[int] = Field(default=None, nullable=True)
    disable_tcp_switch: Optional[str] = Field(default=None, nullable=True)
    follow_early_media_fork: Optional[str] = Field(default=None, nullable=True)
    accept_multiple_sdp_answers: Optional[str] = Field(default=None, nullable=True)
    disable_rport: Optional[str] = Field(default=None, nullable=True)


class PsTransports(SQLModel, table=True):
    __tablename__ = 'ps_transports'
    id: str = Field(primary_key=True)
    async_operations: Optional[int] = Field(default=None, nullable=True)
    bind: Optional[str] = Field(default=None, nullable=True)
    ca_list_file: Optional[str] = Field(default=None, nullable=True)
    cert_file: Optional[str] = Field(default=None, nullable=True)
    cipher: Optional[str] = Field(default=None, nullable=True)
    domain: Optional[str] = Field(default=None, nullable=True)
    external_media_address: Optional[str] = Field(default=None, nullable=True)
    external_signaling_address: Optional[str] = Field(default=None, nullable=True)
    external_signaling_port: Optional[int] = Field(default=None, nullable=True)
    method: Optional[str] = Field(default=None, nullable=True)
    local_net: Optional[str] = Field(default=None, nullable=True)
    password: Optional[str] = Field(default=None, nullable=True)
    priv_key_file: Optional[str] = Field(default=None, nullable=True)
    protocol: Optional[str] = Field(default=None, nullable=True)
    require_client_cert: Optional[str] = Field(default=None, nullable=True)
    verify_client: Optional[str] = Field(default=None, nullable=True)
    verify_server: Optional[str] = Field(default=None, nullable=True)
    tos: Optional[str] = Field(default=None, nullable=True)
    cos: Optional[int] = Field(default=None, nullable=True)
    allow_reload: Optional[str] = Field(default=None, nullable=True)
    symmetric_transport: Optional[str] = Field(default=None, nullable=True)
    allow_wildcard_certs: Optional[str] = Field(default=None, nullable=True)
    tcp_keepalive_enable: Optional[int] = Field(default=None, nullable=True)
    tcp_keepalive_idle_time: Optional[int] = Field(default=None, nullable=True)
    tcp_keepalive_interval_time: Optional[int] = Field(default=None, nullable=True)
    tcp_keepalive_probe_count: Optional[int] = Field(default=None, nullable=True)


class QueueMembers(SQLModel, table=True):
    __tablename__ = 'queue_members'
    queue_name: str = Field(primary_key=True)
    interface: str = Field(primary_key=True)
    membername: Optional[str] = Field(default=None, nullable=True)
    state_interface: Optional[str] = Field(default=None, nullable=True)
    penalty: Optional[int] = Field(default=None, nullable=True)
    paused: Optional[int] = Field(default=None, nullable=True)
    uniqueid: int = Field()
    wrapuptime: Optional[int] = Field(default=None, nullable=True)
    ringinuse: Optional[str] = Field(default=None, nullable=True)
    reason_paused: Optional[str] = Field(default=None, nullable=True)


class QueueRules(SQLModel, table=True):
    __tablename__ = 'queue_rules'
    rule_name: str = Field(primary_key=True)
    time: str = Field(primary_key=True)
    min_penalty: Optional[str] = Field(default=None)
    max_penalty: Optional[str] = Field(default=None)


class Queues(SQLModel, table=True):
    __tablename__ = 'queues'
    name: str = Field(primary_key=True)
    musiconhold: Optional[str] = Field(default=None, nullable=True)
    announce: Optional[str] = Field(default=None, nullable=True)
    context: Optional[str] = Field(default=None, nullable=True)
    timeout: Optional[int] = Field(default=None, nullable=True)
    ringinuse: Optional[str] = Field(default=None, nullable=True)
    setinterfacevar: Optional[str] = Field(default=None, nullable=True)
    setqueuevar: Optional[str] = Field(default=None, nullable=True)
    setqueueentryvar: Optional[str] = Field(default=None, nullable=True)
    monitor_format: Optional[str] = Field(default=None, nullable=True)
    membermacro: Optional[str] = Field(default=None, nullable=True)
    membergosub: Optional[str] = Field(default=None, nullable=True)
    queue_youarenext: Optional[str] = Field(default=None, nullable=True)
    queue_thereare: Optional[str] = Field(default=None, nullable=True)
    queue_callswaiting: Optional[str] = Field(default=None, nullable=True)
    queue_quantity1: Optional[str] = Field(default=None, nullable=True)
    queue_quantity2: Optional[str] = Field(default=None, nullable=True)
    queue_holdtime: Optional[str] = Field(default=None, nullable=True)
    queue_minutes: Optional[str] = Field(default=None, nullable=True)
    queue_minute: Optional[str] = Field(default=None, nullable=True)
    queue_seconds: Optional[str] = Field(default=None, nullable=True)
    queue_thankyou: Optional[str] = Field(default=None, nullable=True)
    queue_callerannounce: Optional[str] = Field(default=None, nullable=True)
    queue_reporthold: Optional[str] = Field(default=None, nullable=True)
    announce_frequency: Optional[int] = Field(default=None, nullable=True)
    announce_to_first_user: Optional[str] = Field(default=None, nullable=True)
    min_announce_frequency: Optional[int] = Field(default=None, nullable=True)
    announce_round_seconds: Optional[int] = Field(default=None, nullable=True)
    announce_holdtime: Optional[str] = Field(default=None, nullable=True)
    announce_position: Optional[str] = Field(default=None, nullable=True)
    announce_position_limit: Optional[int] = Field(default=None, nullable=True)
    periodic_announce: Optional[str] = Field(default=None, nullable=True)
    periodic_announce_frequency: Optional[int] = Field(default=None, nullable=True)
    relative_periodic_announce: Optional[str] = Field(default=None, nullable=True)
    random_periodic_announce: Optional[str] = Field(default=None, nullable=True)
    retry: Optional[int] = Field(default=None, nullable=True)
    wrapuptime: Optional[int] = Field(default=None, nullable=True)
    penaltymemberslimit: Optional[int] = Field(default=None, nullable=True)
    autofill: Optional[str] = Field(default=None, nullable=True)
    monitor_type: Optional[str] = Field(default=None, nullable=True)
    autopause: Optional[str] = Field(default=None, nullable=True)
    autopausedelay: Optional[int] = Field(default=None, nullable=True)
    autopausebusy: Optional[str] = Field(default=None, nullable=True)
    autopauseunavail: Optional[str] = Field(default=None, nullable=True)
    maxlen: Optional[int] = Field(default=None, nullable=True)
    servicelevel: Optional[int] = Field(default=None, nullable=True)
    strategy: Optional[str] = Field(default=None, nullable=True)
    joinempty: Optional[str] = Field(default=None, nullable=True)
    leavewhenempty: Optional[str] = Field(default=None, nullable=True)
    reportholdtime: Optional[str] = Field(default=None, nullable=True)
    memberdelay: Optional[int] = Field(default=None, nullable=True)
    weight: Optional[int] = Field(default=None, nullable=True)
    timeoutrestart: Optional[str] = Field(default=None, nullable=True)
    defaultrule: Optional[str] = Field(default=None, nullable=True)
    timeoutpriority: Optional[str] = Field(default=None, nullable=True)
    log_restricted_caller_id: Optional[str] = Field(default=None, nullable=True)


class Sippeers(SQLModel, table=True):
    __tablename__ = 'sippeers'
    id: int = Field(primary_key=True)
    name: str = Field()
    ipaddr: Optional[str] = Field(default=None, nullable=True)
    port: Optional[int] = Field(default=None, nullable=True)
    regseconds: Optional[int] = Field(default=None, nullable=True)
    defaultuser: Optional[str] = Field(default=None, nullable=True)
    fullcontact: Optional[str] = Field(default=None, nullable=True)
    regserver: Optional[str] = Field(default=None, nullable=True)
    useragent: Optional[str] = Field(default=None, nullable=True)
    lastms: Optional[int] = Field(default=None, nullable=True)
    host: Optional[str] = Field(default=None, nullable=True)
    type: Optional[str] = Field(default=None, nullable=True)
    context: Optional[str] = Field(default=None, nullable=True)
    permit: Optional[str] = Field(default=None, nullable=True)
    deny: Optional[str] = Field(default=None, nullable=True)
    secret: Optional[str] = Field(default=None, nullable=True)
    md5secret: Optional[str] = Field(default=None, nullable=True)
    remotesecret: Optional[str] = Field(default=None, nullable=True)
    transport: Optional[str] = Field(default=None, nullable=True)
    dtmfmode: Optional[str] = Field(default=None, nullable=True)
    directmedia: Optional[str] = Field(default=None, nullable=True)
    nat: Optional[str] = Field(default=None, nullable=True)
    callgroup: Optional[str] = Field(default=None, nullable=True)
    pickupgroup: Optional[str] = Field(default=None, nullable=True)
    language: Optional[str] = Field(default=None, nullable=True)
    disallow: Optional[str] = Field(default=None, nullable=True)
    allow: Optional[str] = Field(default=None, nullable=True)
    insecure: Optional[str] = Field(default=None, nullable=True)
    trustrpid: Optional[str] = Field(default=None, nullable=True)
    progressinband: Optional[str] = Field(default=None, nullable=True)
    promiscredir: Optional[str] = Field(default=None, nullable=True)
    useclientcode: Optional[str] = Field(default=None, nullable=True)
    accountcode: Optional[str] = Field(default=None, nullable=True)
    setvar: Optional[str] = Field(default=None, nullable=True)
    callerid: Optional[str] = Field(default=None, nullable=True)
    amaflags: Optional[str] = Field(default=None, nullable=True)
    callcounter: Optional[str] = Field(default=None, nullable=True)
    busylevel: Optional[int] = Field(default=None, nullable=True)
    allowoverlap: Optional[str] = Field(default=None, nullable=True)
    allowsubscribe: Optional[str] = Field(default=None, nullable=True)
    videosupport: Optional[str] = Field(default=None, nullable=True)
    maxcallbitrate: Optional[int] = Field(default=None, nullable=True)
    rfc2833compensate: Optional[str] = Field(default=None, nullable=True)
    mailbox: Optional[str] = Field(default=None, nullable=True)
    # TODO: Field 'session-timers' is not a valid Python identifier. Skipped for now.
    # TODO: Field 'session-expires' is not a valid Python identifier. Skipped for now.
    # TODO: Field 'session-minse' is not a valid Python identifier. Skipped for now.
    # TODO: Field 'session-refresher' is not a valid Python identifier. Skipped for now.
    t38pt_usertpsource: Optional[str] = Field(default=None, nullable=True)
    regexten: Optional[str] = Field(default=None, nullable=True)
    fromdomain: Optional[str] = Field(default=None, nullable=True)
    fromuser: Optional[str] = Field(default=None, nullable=True)
    qualify: Optional[str] = Field(default=None, nullable=True)
    defaultip: Optional[str] = Field(default=None, nullable=True)
    rtptimeout: Optional[int] = Field(default=None, nullable=True)
    rtpholdtimeout: Optional[int] = Field(default=None, nullable=True)
    sendrpid: Optional[str] = Field(default=None, nullable=True)
    outboundproxy: Optional[str] = Field(default=None, nullable=True)
    callbackextension: Optional[str] = Field(default=None, nullable=True)
    timert1: Optional[int] = Field(default=None, nullable=True)
    timerb: Optional[int] = Field(default=None, nullable=True)
    qualifyfreq: Optional[int] = Field(default=None, nullable=True)
    constantssrc: Optional[str] = Field(default=None, nullable=True)
    contactpermit: Optional[str] = Field(default=None, nullable=True)
    contactdeny: Optional[str] = Field(default=None, nullable=True)
    usereqphone: Optional[str] = Field(default=None, nullable=True)
    textsupport: Optional[str] = Field(default=None, nullable=True)
    faxdetect: Optional[str] = Field(default=None, nullable=True)
    buggymwi: Optional[str] = Field(default=None, nullable=True)
    auth: Optional[str] = Field(default=None, nullable=True)
    fullname: Optional[str] = Field(default=None, nullable=True)
    trunkname: Optional[str] = Field(default=None, nullable=True)
    cid_number: Optional[str] = Field(default=None, nullable=True)
    callingpres: Optional[str] = Field(default=None, nullable=True)
    mohinterpret: Optional[str] = Field(default=None, nullable=True)
    mohsuggest: Optional[str] = Field(default=None, nullable=True)
    parkinglot: Optional[str] = Field(default=None, nullable=True)
    hasvoicemail: Optional[str] = Field(default=None, nullable=True)
    subscribemwi: Optional[str] = Field(default=None, nullable=True)
    vmexten: Optional[str] = Field(default=None, nullable=True)
    autoframing: Optional[str] = Field(default=None, nullable=True)
    rtpkeepalive: Optional[int] = Field(default=None, nullable=True)
    # TODO: Field 'call-limit' is not a valid Python identifier. Skipped for now.
    g726nonstandard: Optional[str] = Field(default=None, nullable=True)
    ignoresdpversion: Optional[str] = Field(default=None, nullable=True)
    allowtransfer: Optional[str] = Field(default=None, nullable=True)
    dynamic: Optional[str] = Field(default=None, nullable=True)
    path: Optional[str] = Field(default=None, nullable=True)
    supportpath: Optional[str] = Field(default=None, nullable=True)


class StirTn(SQLModel, table=True):
    __tablename__ = 'stir_tn'
    id: str = Field(primary_key=True)
    private_key_file: Optional[str] = Field(default=None, nullable=True)
    public_cert_url: Optional[str] = Field(default=None, nullable=True)
    attest_level: Optional[str] = Field(default=None, nullable=True)
    send_mky: Optional[str] = Field(default=None, nullable=True)


class Voicemail(SQLModel, table=True):
    __tablename__ = 'voicemail'
    uniqueid: int = Field(primary_key=True)
    context: str = Field()
    mailbox: str = Field()
    password: str = Field()
    fullname: Optional[str] = Field(default=None, nullable=True)
    alias: Optional[str] = Field(default=None, nullable=True)
    email: Optional[str] = Field(default=None, nullable=True)
    pager: Optional[str] = Field(default=None, nullable=True)
    attach: Optional[str] = Field(default=None, nullable=True)
    attachfmt: Optional[str] = Field(default=None, nullable=True)
    serveremail: Optional[str] = Field(default=None, nullable=True)
    language: Optional[str] = Field(default=None, nullable=True)
    tz: Optional[str] = Field(default=None, nullable=True)
    deletevoicemail: Optional[str] = Field(default=None, nullable=True)
    saycid: Optional[str] = Field(default=None, nullable=True)
    sendvoicemail: Optional[str] = Field(default=None, nullable=True)
    review: Optional[str] = Field(default=None, nullable=True)
    tempgreetwarn: Optional[str] = Field(default=None, nullable=True)
    operator: Optional[str] = Field(default=None, nullable=True)
    envelope: Optional[str] = Field(default=None, nullable=True)
    sayduration: Optional[int] = Field(default=None, nullable=True)
    forcename: Optional[str] = Field(default=None, nullable=True)
    forcegreetings: Optional[str] = Field(default=None, nullable=True)
    callback: Optional[str] = Field(default=None, nullable=True)
    dialout: Optional[str] = Field(default=None, nullable=True)
    exitcontext: Optional[str] = Field(default=None, nullable=True)
    maxmsg: Optional[int] = Field(default=None, nullable=True)
    volgain: Optional[float] = Field(default=None, nullable=True)
    imapuser: Optional[str] = Field(default=None, nullable=True)
    imappassword: Optional[str] = Field(default=None, nullable=True)
    imapserver: Optional[str] = Field(default=None, nullable=True)
    imapport: Optional[str] = Field(default=None, nullable=True)
    imapflags: Optional[str] = Field(default=None, nullable=True)
    stamp: Optional[datetime] = Field(default=None, nullable=True)


class QueueLog(SQLModel, table=True):
    __tablename__ = 'queue_log'
    time: str = Field(primary_key=True)
    callid: str = Field(primary_key=True)
    queuename: str = Field()
    agent: str = Field()
    event: str = Field(primary_key=True)
    data1: Optional[str] = Field(default=None, nullable=True)
    data2: Optional[str] = Field(default=None, nullable=True)
    data3: Optional[str] = Field(default=None, nullable=True)
    data4: Optional[str] = Field(default=None, nullable=True)
    data5: Optional[str] = Field(default=None, nullable=True)

